(() => {
'use strict';
const $=id=>document.getElementById(id), key='hsh-dossier-editor-v1';
const types={diary:'NHẬT KÝ CÔNG TRÌNH',acceptance:'BIÊN BẢN NGHIỆM THU CÔNG VIỆC XÂY DỰNG',defect:'BIÊN BẢN GHI NHẬN DEFECT LIST'};
const originals={diary:'03.NHAT KY CONG TRINH.DOC',acceptance:'07.BBNT CONG VIEC XAY DUNG.doc',defect:'09.BIEN BAN GHI NHAN DEFECT LIST.docx'};
const labels={name:'Dự án / Công trình',package:'Gói thầu',address:'Địa điểm',owner:'Chủ đầu tư',contractor:'Đơn vị thi công',contract:'Hợp đồng số'};
const defaults={name:'CẢI TẠO & XÂY MỚI HOA SEN HOME PHỦ LÝ',package:'Thi công cải tạo và xây mới cửa hàng Hoa Sen Home Phủ Lý',address:'Phủ Lý – Ninh Bình',owner:'TẬP ĐOÀN HOA SEN (HSG)',contractor:'CÔNG TY TNHH TM HOÀNG GIANG',contract:'01/2026/HĐXD/HSG-HG'};
let state={project:{...defaults},records:[]},active,busy=false;
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&Array.isArray(saved.records)&&saved.project)state=saved;}catch(e){$('status').textContent='Không đọc được bản lưu; hãy xuất file để lưu trữ.';}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function save(){try{localStorage.setItem(key,JSON.stringify(state));$('status').textContent='Đã lưu trên máy này';}catch(e){$('status').textContent='Không lưu được trên máy (có thể đã đầy). Hãy xuất file ngay.';}}
function field(k,label,value=''){return `<div class="field"><b>${esc(label)}</b><div class="edit" contenteditable="plaintext-only" role="textbox" aria-label="${esc(label)}" data-key="${k}" data-placeholder="Bấm để điền">${esc(active.fields[k]??value)}</div></div>`;}
function meta(){return `<div class="meta">${Object.entries(labels).map(([k,l])=>`<p><b>${l}:</b> <span data-project="${k}">${esc(state.project[k])}</span></p>`).join('')}</div>`;}
function dateText(){const [y,m,d]=active.date.split('-');return `Ngày ${d} tháng ${m} năm ${y}`;}
function signatures(prefix){return `<div class="signatures">${['CỬA HÀNG TRƯỞNG / TRƯỞNG KHO','PHÒNG ĐTXDCB','ĐƠN VỊ THI CÔNG'].map((s,i)=>`<div><b>${s}</b><br>(Ký và ghi rõ họ tên)${field(prefix+'sig'+i,'Họ tên')}</div>`).join('')}</div>`;}
function photo(k,label){return `<label class="photo-control">${label}<input type="file" accept="image/*" data-photo="${k}"></label>${active.photos[k]?`<img class="photo" src="${active.photos[k]}" alt="${label}">`:''}`;}
function participants(){return ['Phòng ĐTXDCB','Cửa hàng trưởng / Trưởng kho','Phòng KSNB/KST/KSBH/KSTK (nếu có)','Đơn vị thi công'].map((s,i)=>field('participant'+i,s+' — Họ tên, chức vụ')).join('');}
function render(){
$('date').value=active.date;$('type').value=active.type;$('original').href='assets/hoa-sen/docs/'+encodeURIComponent(originals[active.type]);
let pages=[];
if(active.type==='diary'){
pages.push(`<div class="cover"><div class="national">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM<br>Độc lập – Tự do – Hạnh phúc</div><h1>NHẬT KÝ CÔNG TRÌNH</h1>${field('volume','Quyển','01')}${meta()}<p class="doc-date">${dateText()}</p></div>`);
pages.push(`<h1>THÔNG TIN NHẬT KÝ THI CÔNG</h1>${meta()}${field('start','Bắt đầu thi công','10/09/2026')}${field('end','Kết thúc theo kế hoạch','09/11/2026')}${field('actual','Kết thúc thực tế')}${field('register','Số trang, đánh số từ… đến… và đóng dấu giáp lai')}${field('staff','Danh sách cán bộ: Họ tên – trình độ – chức vụ – thời gian tham gia – chữ ký mẫu')}${signatures('register')}`);
for(let i=0;i<active.count;i++)pages.push(`<h1>NHẬT KÝ THI CÔNG</h1>${meta()}${field('day'+i,'Ngày ghi nhật ký',dateText())}${field('weather'+i,'1. Thời tiết sáng / chiều')}${field('workers'+i,'2. Số công nhân trên công trường')}${field('managers'+i,'3. Cán bộ quản lý')}${field('equipment'+i,'4. Thiết bị thi công')}${field('work'+i,'5. Nội dung công việc')}${field('opinion'+i,'Ý kiến của đơn vị thi công')}${field('review'+i,'Nhận xét của chủ đầu tư')}${signatures('day'+i)}`);
}else if(active.type==='acceptance'){
pages.push(`<div class="national">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM<br>Độc lập – Tự do – Hạnh phúc</div><h1>${types.acceptance}</h1>${meta()}<p class="doc-date">${dateText()}</p>${field('number','Biên bản số')}${field('category','Hạng mục')}${field('subject','1. Đối tượng nghiệm thu')}<h3>2. Thành phần trực tiếp tham gia nghiệm thu</h3>${participants()}${field('time','3. Thời gian bắt đầu / kết thúc và địa điểm nghiệm thu',dateText())}`);
pages.push(`<h1>ĐÁNH GIÁ VÀ KẾT LUẬN NGHIỆM THU</h1>${meta()}<p class="doc-date">${dateText()}</p>${field('basis','4. Tài liệu làm căn cứ nghiệm thu','Phiếu yêu cầu nghiệm thu: \nBản vẽ thi công được duyệt / thay đổi thiết kế: \nTiêu chuẩn và chỉ dẫn kỹ thuật áp dụng: \nKết quả kiểm tra, thí nghiệm vật liệu, thiết bị: \nNhật ký thi công / giám sát: \nBiên bản nghiệm thu nội bộ: ')}${field('quality','Chất lượng công việc so với thiết kế và yêu cầu kỹ thuật')}${field('other','Các ý kiến khác')}${field('conclusion','5. Kết luận: Chấp nhận / không chấp nhận; điều kiện triển khai tiếp')}${field('attachments','Hồ sơ và phụ lục kèm theo')}${field('controlsignature','Phòng KSNB/KST/KSBH/KSTK (nếu có) — Họ tên, chữ ký')}${signatures('accept')}`);
for(let i=1;i<active.count;i++)pages.push(`<h1>PHỤ LỤC NGHIỆM THU ${i}</h1>${meta()}${field('appendix'+i,'Nội dung bổ sung')}${signatures('appendix'+i)}`);
}else{
pages.push(`<h1>${types.defect}</h1>${meta()}<p class="doc-date">${dateText()}</p>${field('category','Hạng mục')}${field('time','Thời gian kiểm tra',dateText())}<h3>Thành phần tham gia</h3>${participants()}<p>Các bên cùng tiến hành kiểm tra tại công trình và ghi nhận các nội dung chi tiết ở các trang tiếp theo.</p>${field('controlsignature','Phòng KSNB/KST/KSBH/KSTK — Họ tên, chữ ký')}${signatures('defect')}`);
for(let i=0;i<active.count;i++)pages.push(`<h1>DEFECT LIST — MỤC ${i+1}</h1>${meta()}<p class="doc-date">${dateText()}</p>${field('issue'+i,'Nội dung tồn tại')}${field('location'+i,'Vị trí / khu vực')}${photo('before'+i,'Hình ảnh minh họa')}${field('fix'+i,'Biện pháp khắc phục / sửa chữa')}${field('from'+i,'Thời gian bắt đầu')}${field('to'+i,'Thời gian kết thúc')}${photo('after'+i,'Hình ảnh sau khắc phục')}${field('note'+i,'Ghi chú / xác nhận đóng lỗi')}`);
}
$('pages').innerHTML=pages.map((p,i)=>`<article class="paper">${p}<div class="page-number">${i+1} / ${pages.length}</div></article>`).join('');list();
}
function list(){$('records').innerHTML=state.records.filter(r=>r.type===active.type).map(r=>`<option value="${r.id}" ${r.id===active.id?'selected':''}>${esc(r.date)} • Hồ sơ ${state.records.indexOf(r)+1}</option>`).join('');}
function create(type){active={id:crypto.randomUUID(),type,date:today(),fields:{},photos:{},count:1};state.records.push(active);save();render();}
$('project').innerHTML=Object.entries(labels).map(([k,l])=>`<label>${l}<input data-common="${k}" value="${esc(state.project[k])}"></label>`).join('');
$('project').addEventListener('input',e=>{const k=e.target.dataset.common;if(!k)return;state.project[k]=e.target.value;document.querySelectorAll('[data-project]').forEach(n=>{if(n.dataset.project===k)n.textContent=e.target.value;});save();});
$('pages').addEventListener('input',e=>{const k=e.target.dataset.key;if(k){active.fields[k]=e.target.innerText;save();}});
$('pages').addEventListener('change',async e=>{const k=e.target.dataset.photo,f=e.target.files?.[0];if(!k||!f)return;if(!f.type.startsWith('image/'))return;try{const bitmap=await createImageBitmap(f),c=document.createElement('canvas'),ratio=Math.min(1,1200/bitmap.width);c.width=bitmap.width*ratio;c.height=bitmap.height*ratio;c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();active.photos[k]=c.toDataURL('image/jpeg',.8);save();render();}catch(err){$('status').textContent='Không đọc được ảnh. Hãy chọn ảnh JPG hoặc PNG.';}});
$('date').onchange=()=>{if(!$('date').value)return;active.date=$('date').value;save();render();};
$('new').onclick=()=>create($('type').value);$('type').onchange=()=>{const r=state.records.findLast(r=>r.type===$('type').value);if(r){active=r;render();}else create($('type').value);};
$('records').onchange=()=>{active=state.records.find(r=>r.id===$('records').value);render();};$('add').onclick=()=>{active.count++;save();render();};
async function exportFile(format){if(busy)return;if(Object.keys(labels).some(k=>!state.project[k]?.trim())){$('status').textContent='Hãy điền đủ thông tin công trình dùng chung trước khi xuất.';$('project').querySelector('input:placeholder-shown')?.focus();return;}busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);$('status').textContent='Đang tạo file…';
const stage=document.createElement('div');stage.className='exporting';stage.style.cssText='position:absolute;left:-12000px;top:0;width:794px';document.body.append(stage);
try{await document.fonts.ready;const pdf=format==='pdf'?new window.jspdf.jsPDF({unit:'mm',format:'a4'}):null;let number=0;
for(const paper of document.querySelectorAll('.paper')){const clone=paper.cloneNode(true);clone.style.margin='0';clone.style.boxShadow='none';stage.replaceChildren(clone);await Promise.all([...clone.images||clone.querySelectorAll('img')].map(im=>im.decode().catch(()=>{})));const canvas=await html2canvas(clone,{scale:1.5,backgroundColor:'#ffffff',logging:false});const max=Math.ceil(canvas.width*297/210)+2;let y=0;while(y<canvas.height){let end=Math.min(y+max,canvas.height);if(end<canvas.height){const ctx=canvas.getContext('2d');for(let row=end;row>end-150;row--){const pixels=ctx.getImageData(0,row,canvas.width,1).data;let ink=false;for(let x=0;x<pixels.length;x+=4){if(pixels[x]<235||pixels[x+1]<235||pixels[x+2]<235){ink=true;break;}}if(!ink){end=row;break;}}}const part=document.createElement('canvas');part.width=canvas.width;part.height=max;const ctx=part.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,part.width,part.height);ctx.drawImage(canvas,0,y,canvas.width,end-y,0,0,canvas.width,end-y);number++;if(pdf){if(number>1)pdf.addPage();pdf.addImage(part.toDataURL('image/jpeg',.95),'JPEG',0,0,210,297);}else{const blob=await new Promise(resolve=>part.toBlob(resolve,'image/png'));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${active.type}-${active.date}-trang-${number}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}y=end;}}
if(pdf)pdf.save(`${active.type}-${active.date}.pdf`);$('status').textContent=format==='png'?`Đã xuất ${number} ảnh. Cho phép tải nhiều file nếu trình duyệt hỏi.`:`Đã xuất PDF ${number} trang`;
}catch(e){$('status').textContent='Xuất file chưa thành công. Vui lòng thử lại. '+e.message;}finally{stage.remove();busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
$('pdf').onclick=()=>exportFile('pdf');$('png').onclick=()=>exportFile('png');
const requested=new URLSearchParams(location.search).get('type');const type=types[requested]?requested:'diary';active=state.records.findLast(r=>r.type===type);if(active)render();else create(type);
})();

