(() => {
'use strict';
const root='https://api.github.com/repos/luckyluong2k-collab/tonhoasen', base='dossier-exports';
let token='', queue=Promise.resolve();
async function api(path,method='GET',body){const r=await fetch(root+path,{method,cache:'no-store',headers:{Accept:'application/vnd.github+json',...(token?{Authorization:'Bearer '+token}:{} )},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(90000)});if(!r.ok){const e=Error(`GitHub (${r.status}): ${r.status===401||r.status===403?'kiểm tra quyền kết nối.':'chưa hoàn tất lưu; hãy thử lại.'}`);e.status=r.status;throw e;}return r.json();}
const decode=s=>new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\s/g,'')),c=>c.charCodeAt(0)));
async function json(path,ref='main'){const r=await fetch(root+'/contents/'+path+'?ref='+encodeURIComponent(ref),{cache:'no-store',headers:{Accept:'application/vnd.github.raw+json',...(token?{Authorization:'Bearer '+token}:{})},signal:AbortSignal.timeout(90000)});if(!r.ok)throw Error('Chưa đọc được danh mục GitHub ('+r.status+').');return r.json();}
function checkIndex(x){if(x?.schema!=='hsh-github-archive-v1'||!Array.isArray(x.entries)||x.entries.some(e=>!/^EXP-[a-zA-Z0-9-]+$/.test(e.id)||!['diary','acceptance','defect'].includes(e.type)||(typeof e.filename!=='string'||!e.filename.length||/[\\/:*?"<>|\u0000-\u001f]/.test(e.filename))||e.filename.includes('..')||!/^[a-f0-9]{64}$/.test(e.sha256)||typeof e.exportedAt!=='string'))throw Error('Danh mục GitHub không hợp lệ.');return x;}
async function list(ref='main'){return checkIndex(await json(base+'/index.json',ref));}
async function read(id){if(!/^EXP-[a-zA-Z0-9-]+$/.test(id))throw Error('Mã hồ sơ không hợp lệ.');const head=(await api('/git/ref/heads/main')).object.sha;const index=await list(head),item=index.entries.find(e=>e.id===id);if(!item)throw Error('Chưa tìm thấy bản lưu trên GitHub.');const meta=await json(base+'/'+id+'/record.json',head);if(meta.id!==id||meta.filename!==item.filename||meta.sha256!==item.sha256)throw Error('Thông tin GitHub không khớp.');const r=await fetch('https://raw.githubusercontent.com/luckyluong2k-collab/tonhoasen/'+head+'/'+base+'/'+id+'/'+item.filename,{cache:'no-store',signal:AbortSignal.timeout(90000)});if(!r.ok)throw Error('Chưa tải được file GitHub.');return {...meta,blob:await r.blob(),githubSaved:true,folderSaved:false};}
async function upload(entry){if(!token)throw Error('Hãy kết nối GitHub để lưu trực tuyến.');if(entry.blob.size>95000000)throw Error('File quá lớn để lưu GitHub (giới hạn của trang: 95 MB). Hãy dùng bản sao ZIP/thư mục.');const bytes=new Uint8Array(await entry.blob.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const file=await api('/git/blobs','POST',{encoding:'base64',content:btoa(binary)});const {blob,folderSaved,githubSaved,...meta}=entry;const {snapshot,...summary}=meta;
for(let attempt=0;attempt<3;attempt++){const head=(await api('/git/ref/heads/main')).object.sha;const old=await list(head),existing=old.entries.find(e=>e.id===entry.id);if(existing){if(existing.sha256!==entry.sha256)throw Error('Mã hồ sơ đã tồn tại với nội dung khác.');const saved=await read(entry.id);const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await saved.blob.arrayBuffer()))).map(x=>x.toString(16).padStart(2,'0')).join('');if(digest!==entry.sha256)throw Error('Bản lưu GitHub không khớp.');return;}
const parent=await api('/git/commits/'+head);const tree=await api('/git/trees','POST',{base_tree:parent.tree.sha,tree:[{path:base+'/'+entry.id+'/'+entry.filename,mode:'100644',type:'blob',sha:file.sha},{path:base+'/'+entry.id+'/record.json',mode:'100644',type:'blob',content:JSON.stringify(meta)},{path:base+'/index.json',mode:'100644',type:'blob',content:JSON.stringify({schema:old.schema,entries:[...old.entries,summary]})}]});const commit=await api('/git/commits','POST',{message:'Archive dossier '+entry.id,tree:tree.sha,parents:[head]});try{await api('/git/refs/heads/main','PATCH',{sha:commit.sha,force:false});return;}catch(e){if(![409,422].includes(e.status)||attempt===2)throw e;}}
}
window.HSHGitHub={list,read,get connected(){return !!token;},async connect(value){token=value.trim();try{const repo=await api('');if(!repo.permissions?.push)throw Error('Tài khoản chưa có quyền ghi kho hồ sơ.');}catch(e){token='';throw e;}},disconnect(){token='';},save(entry){const next=queue.catch(()=>{}).then(()=>upload(entry));queue=next;return next;}};
})();
