(()=>{'use strict';
const SHEET_ID='1QfMS1lw68LlCQCmaR0weB5WHq9DjfRg4HKrbTjRQ_3Y';
const CLIENT_ID='205763163202-bjketnf7ajl4pdsoq1peadjhufbrjh0p.apps.googleusercontent.com';
const TAB='NHẬT KÝ DỮ LIỆU';
let weather=['Nắng','Nắng nhẹ','Nắng nóng','Nhiều mây','Âm u','Mưa nhỏ','Mưa rào','Mưa lớn','Giông','Khô ráo'];
const states=['Nháp','Đã nhập','Đã kiểm tra','Đã chốt'];
const suggestion={env:'Thu gom phế thải, vệ sinh khu vực thi công cuối ca; đảm bảo lối đi thông thoáng.',safe:'Kiểm tra PPE và điều kiện an toàn trước khi thi công; nhắc nhở công nhân tuân thủ biện pháp an toàn.'};
let token='',tokenClient=null,data=[],meta=[],config={},saving=false;
const draftKey='hsh-sheet-diary-draft-v1';
try{const saved=JSON.parse(localStorage.getItem(draftKey)||'null');if(saved){data=saved.data;meta=saved.meta;config=saved.config||{};}}catch(_){}
function persist(){try{localStorage.setItem(draftKey,JSON.stringify({data,meta,config}));}catch(e){setProg('Không lưu được bản nháp trên máy: '+e.message);throw e;}}
function collect(){document.querySelectorAll('#rows tr').forEach((tr,i)=>{const row=readRow(tr);if(JSON.stringify(row)!==JSON.stringify(data[i])){data[i]=row;meta[i].dirty=true;}});persist();}
const normalize=r=>Array.from({length:13},(_,i)=>String(r?.[i]??''));
function applyConfig(){suggestion.env=config['Gợi ý vệ sinh môi trường']||suggestion.env;suggestion.safe=config['Gợi ý an toàn lao động']||suggestion.safe;if(config['Danh sách thời tiết'])weather=config['Danh sách thời tiết'].split('|').map(s=>s.trim()).filter(Boolean);}
applyConfig();

const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setStatus(s){$('status').textContent=s} function setProg(s){$('progress').textContent=s||''}
function isoToVi(v){if(!v)return ''; if(/^\d{4}-\d{2}-\d{2}$/.test(v)){const [y,m,d]=v.split('-');return `${d}/${m}/${y}`}return v}
function viToIso(v){const m=String(v||'').match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:(/^\d{4}-\d{2}-\d{2}$/.test(v)?v:'')}
function opts(list,val){return list.map(x=>`<option ${x===val?'selected':''}>${esc(x)}</option>`).join('')}
function render(){const body=$('rows');body.innerHTML='';data.forEach((r,i)=>{const tr=document.createElement('tr');tr.dataset.i=i;tr.innerHTML=`<td><input class="date" type="date" data-k="0" value="${viToIso(r[0])}"></td><td><select class="weather" data-k="1"><option></option>${opts(weather,r[1])}</select></td><td><select class="weather" data-k="2"><option></option>${opts(weather,r[2])}</select></td><td><textarea data-k="3">${esc(r[3])}</textarea></td><td><textarea data-k="4">${esc(r[4])}</textarea></td><td><input class="small" type="number" min="0" data-k="5" value="${esc(r[5])}"></td><td><input class="small" type="number" min="0" data-k="6" value="${esc(r[6])}"></td><td><textarea data-k="7">${esc(r[7])}</textarea></td><td><textarea data-k="8">${esc(r[8])}</textarea></td><td><textarea data-k="9">${esc(r[9])}</textarea></td><td><textarea data-k="10">${esc(r[10])}</textarea></td><td><textarea data-k="11">${esc(r[11])}</textarea></td><td><select class="state" data-k="12">${opts(states,r[12]||'Nháp')}</select></td><td><div class="row-actions"><button class="mini save" data-act="save">Lưu</button><button class="mini suggest" data-act="suggest">Gợi ý</button><button class="mini delete" data-act="delete">Xóa</button></div></td>`;body.appendChild(tr)}); if(!data.length)addLocalRow();}
function readRow(tr){const a=Array(13).fill('');tr.querySelectorAll('[data-k]').forEach(el=>{const k=+el.dataset.k;a[k]=k===0?isoToVi(el.value):el.value});return a}
function addLocalRow(src){collect();meta.push({row:null,dirty:true,base:null});const today=new Date();const iso=today.toISOString().slice(0,10);const r=src?[...src]:[isoToVi(iso),'','','','','','','','','','','','Nháp'];data.push(r);persist();render();requestAnimationFrame(()=>{const t=$('rows').lastElementChild;t?.scrollIntoView({block:'center'});t?.querySelector('input')?.focus()})}
async function auth(){if(token)return token;if(!window.google?.accounts?.oauth2)throw Error('Google chưa tải xong. Hãy thử lại sau vài giây.');return new Promise((resolve,reject)=>{tokenClient=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:'https://www.googleapis.com/auth/spreadsheets',callback:r=>{if(r.error)return reject(Error(r.error));token=r.access_token;setStatus('Đã kết nối Google Sheet');resolve(token)},error_callback:()=>reject(Error('Cửa sổ đăng nhập Google bị đóng hoặc chặn.'))});tokenClient.requestAccessToken({prompt:''})})}
async function api(url,opt={},retry=true){await auth();const r=await fetch(url,{...opt,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(opt.headers||{})}});if(r.status===401){token='';if(retry)return api(url,opt,false);throw Error('Phiên Google hết hạn. Kết nối lại để tiếp tục.');}if(!r.ok)throw Error('Google Sheets lỗi '+r.status+': '+await r.text());return r.status===204?null:r.json()}
async function load(){if(saving)return;collect();setProg('Đang tải…');try{
 const range=encodeURIComponent(`'${TAB}'!A2:M`);
 const j=await api(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${range}`);
 const pending=data.map((r,i)=>({r,m:meta[i]})).filter(x=>x.m.dirty&&x.r.slice(1,12).some(v=>String(v||'').trim()));
 for(const x of pending.filter(x=>x.m.uncertain)){
 const matches=(j.values||[]).map((r,i)=>({r:normalize(r),row:i+2})).filter(v=>JSON.stringify(v.r)===JSON.stringify(x.r));
 if(matches.length===1){x.m.row=matches[0].row;x.m.base=matches[0].r;x.m.dirty=false;x.m.uncertain=false;}
 else if(matches.length===0)x.m.uncertain=false;
 }
 const next=[],maps=[];
 (j.values||[]).forEach((r,i)=>{if(!r.some(v=>String(v||'').trim()))return;const row=i+2,local=pending.find(x=>x.m.row===row);next.push(local?local.r:normalize(r));maps.push(local?local.m:{row,base:normalize(r),dirty:false});});
 for(const x of pending)if(!x.m.row||!maps.some(m=>m.row===x.m.row)){next.push(x.r);maps.push(x.m);}
 data=next;meta=maps;
 let configMessage='';try{const c=await api(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${encodeURIComponent("'CẤU HÌNH'!A1:B100")}`);config=Object.fromEntries((c.values||[]).filter(r=>r[0]&&r[1]).map(r=>[r[0].trim(),r[1]]));applyConfig();}catch(e){configMessage=' · Chưa tải cấu hình: '+e.message;}
 persist();render();setProg(`${data.length} ngày · Giữ các bản nháp chưa lưu`+configMessage);
 const ds=data.map(r=>viToIso(r[0])).filter(Boolean).sort();if(ds.length){$('fromDate').value=ds[0];$('toDate').value=ds.at(-1);}
 }catch(e){setProg(e.message);}}
async function checkUnchanged(m){const j=await api(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${encodeURIComponent(`'${TAB}'!A${m.row}:M${m.row}`)}`);if(JSON.stringify(normalize(j.values?.[0]))!==JSON.stringify(normalize(m.base)))throw Error('Dòng trên Sheet đã thay đổi hoặc di chuyển. Bản nháp được giữ; hãy đối chiếu Sheet trước khi lưu.');}
async function saveIndex(i){if(saving)return;collect();const row=[...data[i]],m=meta[i];if(!row[0])return alert('Hãy chọn ngày.');if(m.uncertain)return alert('Lần thêm trước chưa xác nhận. Kiểm tra Sheet và tải lại dữ liệu trước khi gửi thêm để tránh trùng.');saving=true;setProg('Đang lưu…');try{
 if(m.row){await checkUnchanged(m);await api(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${encodeURIComponent(`'${TAB}'!A${m.row}:M${m.row}`)}?valueInputOption=RAW`,{method:'PUT',body:JSON.stringify({values:[row]})});}
 else {m.uncertain=true;persist();const result=await api(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${encodeURIComponent(`'${TAB}'!A:M`)}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:'POST',body:JSON.stringify({values:[row]})});const match=result.updates?.updatedRange?.match(/!A(\d+):/);if(!match)throw Error('Chưa xác nhận vị trí dòng mới.');m.row=Number(match[1]);m.uncertain=false;}
 m.base=row;m.dirty=JSON.stringify(data[i])!==JSON.stringify(row);persist();setProg('Đã lưu đúng dòng '+m.row+' trên Sheet.');
 }catch(e){setProg(e.message);}finally{saving=false;}}
async function deleteIndex(i){if(saving||!confirm('Xóa dòng này khỏi bảng dữ liệu?'))return;collect();saving=true;try{const m=meta[i];if(m.uncertain)throw Error('Kiểm tra lần thêm chưa xác nhận trên Sheet trước khi xóa bản nháp.');if(m.row){await checkUnchanged(m);await api(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${encodeURIComponent(`'${TAB}'!A${m.row}:M${m.row}`)}:clear`,{method:'POST',body:'{}'});}data.splice(i,1);meta.splice(i,1);persist();render();setProg('Đã xóa đúng dòng.');}catch(e){setProg(e.message);}finally{saving=false;}}
function fillRow(i){const tr=$('rows').querySelector(`tr[data-i="${i}"]`);if(!tr)return;const e=tr.querySelector('[data-k="8"]'),s=tr.querySelector('[data-k="9"]');if(!e.value.trim())e.value=suggestion.env;if(!s.value.trim())s.value=suggestion.safe;if(!tr.querySelector('[data-k="12"]').value)tr.querySelector('[data-k="12"]').value='Nháp'}
function fillAll(){[...$('rows').children].forEach((_,i)=>fillRow(i));collect();}
function rowHasContent(r){return r.slice(1,12).some(v=>String(v||'').trim())}
function paperHtml(r){return `<div class="paper"><div class="meta">CÔNG TY CỔ PHẦN TẬP ĐOÀN HOA SEN<br><b>${esc(config['Tên công trình']||'CỬA HÀNG HOA SEN HOME PHỦ LÝ')}</b></div><h2>NHẬT KÝ CÔNG TRÌNH</h2><div class="meta">Ngày ${esc(r[0])} • Hạng mục: ${esc(config['Hạng mục']||'Nâng cấp cửa hàng Hoa Sen Home')}<br>${esc(config['Địa điểm']||'')}</div><table><tr><th style="width:27%">Nội dung</th><th>Ghi nhận trong ngày</th></tr><tr><td>1. Thời tiết</td><td>Sáng: ${esc(r[1]||'—')} &nbsp;&nbsp; Chiều: ${esc(r[2]||'—')}</td></tr><tr><td>2. Nhân lực</td><td>Sáng: ${esc(r[5]||'—')} người &nbsp;&nbsp; Chiều: ${esc(r[6]||'—')} người</td></tr><tr><td>3. Máy móc, thiết bị</td><td>${esc(r[7]||'—').replace(/\n/g,'<br>')}</td></tr><tr><td>4. Nội dung thi công</td><td>${esc(r[3]||'—').replace(/\n/g,'<br>')}</td></tr><tr><td>5. Nghiệm thu trong ngày</td><td>${esc(r[4]||'—').replace(/\n/g,'<br>')}</td></tr><tr><td>6. Vệ sinh môi trường</td><td>${esc(r[8]||'—').replace(/\n/g,'<br>')}</td></tr><tr><td>7. An toàn lao động</td><td>${esc(r[9]||'—').replace(/\n/g,'<br>')}</td></tr><tr><td>8. Nhận xét TVGS/CĐT</td><td>${esc(r[10]||'').replace(/\n/g,'<br>')}</td></tr><tr><td>9. Ý kiến nhà thầu</td><td>${esc(r[11]||'').replace(/\n/g,'<br>')}</td></tr></table><div class="sign"><div>ĐẠI DIỆN TVGS/CĐT<span>Ký, ghi rõ họ tên</span></div><div>ĐẠI DIỆN NHÀ THẦU<span>Ký, ghi rõ họ tên</span></div></div></div>`}
async function renderCanvas(r){const stage=$('printStage');stage.innerHTML=paperHtml(r);const el=stage.firstElementChild;await new Promise(x=>requestAnimationFrame(()=>requestAnimationFrame(x)));return html2canvas(el,{scale:2,useCORS:true,backgroundColor:'#fff',logging:false})}
async function onePdfBytes(r){const {jsPDF}=window.jspdf;const canvas=await renderCanvas(r);const doc=new jsPDF({orientation:'p',unit:'mm',format:'a4',compress:true});const img=canvas.toDataURL('image/jpeg',.92);doc.addImage(img,'JPEG',0,0,210,297,undefined,'FAST');return new Uint8Array(doc.output('arraybuffer'))}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),4000)}
async function exportBatch(){collect();const from=$('fromDate').value,to=$('toDate').value;if(!from||!to)return alert('Chọn khoảng ngày cần xuất.');const selected=structuredClone(data).map((r,i)=>({r,i,d:viToIso(r[0])})).filter(x=>x.d&&x.d>=from&&x.d<=to&&rowHasContent(x.r)).sort((a,b)=>a.d.localeCompare(b.d));if(!selected.length)return alert('Không có ngày có dữ liệu trong khoảng đã chọn.');if(!$('combined').checked&&!$('individual').checked)return alert('Chọn PDF hoặc ZIP.');const btn=$('exportNow');btn.disabled=true;const zip={};let combined=null;try{const {jsPDF}=window.jspdf;if($('combined').checked)combined=new jsPDF({orientation:'p',unit:'mm',format:'a4',compress:true});for(let n=0;n<selected.length;n++){const {r,d}=selected[n];setProg(`Đang xuất ${n+1}/${selected.length}: ${r[0]}`);const canvas=await renderCanvas(r);const img=canvas.toDataURL('image/jpeg',.92);if(combined){if(n)combined.addPage();combined.addImage(img,'JPEG',0,0,210,297,undefined,'FAST')}if($('individual').checked){const single=new jsPDF({orientation:'p',unit:'mm',format:'a4',compress:true});single.addImage(img,'JPEG',0,0,210,297,undefined,'FAST');zip[`NK_${d}_${n+1}.pdf`]=new Uint8Array(single.output('arraybuffer'))}}
if(combined){await archiveAndDownload(combined.output('blob'),`Nhật ký thi công-${from}-${to}-xuất-${stamp()}.pdf`,'pdf',selected)}if($('individual').checked){const bytes=fflate.zipSync(zip,{level:6});await archiveAndDownload(new Blob([bytes],{type:'application/zip'}),`Nhật ký thi công-${from}-${to}-xuất-${stamp()}.zip`,'zip',selected)}setProg(`Đã xuất ${selected.length} ngày ✓`)}catch(e){alert('Xuất PDF lỗi: '+e.message);setProg('')}finally{btn.disabled=false}}
$('connect').onclick=()=>auth().then(load).catch(e=>alert(e.message));$('refresh').onclick=load;$('add').onclick=()=>addLocalRow();$('copyYesterday').onclick=()=>{collect();const last=data[data.length-1];if(!last)return addLocalRow();const c=[...last];const d=viToIso(c[0]);if(d){const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+1);c[0]=isoToVi(x.toISOString().slice(0,10))}c[4]='';c[10]='';c[11]='';c[12]='Nháp';addLocalRow(c)};$('fillSuggestions').onclick=fillAll;$('toggleExport').onclick=()=>$('exportPanel').classList.toggle('open');$('exportNow').onclick=exportBatch;
$('rows').onclick=e=>{const b=e.target.closest('[data-act]');if(!b)return;const tr=b.closest('tr'),i=+tr.dataset.i;if(b.dataset.act==='save')saveIndex(i);if(b.dataset.act==='suggest'){fillRow(i);collect();};if(b.dataset.act==='delete')deleteIndex(i)};
$('rows').addEventListener('input',collect);$('rows').addEventListener('change',collect);
window.addEventListener('beforeunload',e=>{if(saving){e.preventDefault();e.returnValue='';}});
const stamp=()=>new Date().toLocaleString('sv-SE',{timeZone:'Asia/Ho_Chi_Minh'}).replace(/[ :]/g,'-')+'-'+String(Date.now()).slice(-3);
async function archiveAndDownload(blob,name,format,selected){
 const snapshot={source:'sheet-diary',project:{name:config['Tên công trình']||'Hoa Sen Home Phủ Lý'},record:{id:crypto.randomUUID(),type:'diary',date:selected[0].d,count:selected.length,fields:{sheetRows:JSON.stringify(selected.map(x=>x.r)),config:JSON.stringify(config)},photos:{}}};
 const archived=await HSHArchive.capture(blob,{snapshot,format,pages:selected.length,filename:name});download(blob,archived.entry.filename);
}
HSHArchive.init(async()=>{throw Error('Bản xuất bảng tính được giữ nguyên. Sửa nhật ký trong bảng phía trên rồi xuất bản mới.');}).catch(e=>setProg(e.message));
setTimeout(()=>{if(window.google?.accounts?.oauth2)setStatus('Sẵn sàng kết nối Google Sheet')},1200);render();
})();
